### ISSUE TITLE
OPENAI_API_KEY Issue

### ISSUE THREAD

**Issue by Franck-E** [legojesus/JarvisGPT#1]
Point 2 on Windows:
Open the "environment" file in this folder and input your OpenAI API key, your username as it is written in the operating system, and any other settings you'd like to change, then rename the file to ".env"

Error:  No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>).

Existing and new key was used, no matter if openai.api_key or OPENAI_API_KEY, always fails.. Or am I missing a step?

**Comment by legojesus** [comment]
I think you might have missed renaming the "Environment" file to ".env" after changing the variables there. 

This should work 100%, the error you are getting indicates the program can't find the API key but it might also mean it can't find the .env file? I should add better handling of this I guess.

**Comment by Franck-E** [comment]
Yes I saw it, and this is not it.
Will try to look further next week.
Thanks anyway for the quick reply.

**Comment by legojesus** [comment]
Hey, I just did a clean test on a new machine and things work out of the box as expected. Here are my steps: 
1. git clone https://github.com/legojesus/JarvisGPT.git
2. CD into the JarvisGPT folder.
3. pip install -r requirements.txt
4. Edit the "environment" file with the api key and my OS username (keeping everything within quotes as shown in the placeholders examples). 
5. Rename the environment file to ".env"
6. run the program with "python main.py". 

I hope you'll find your missing step here.

**Comment by Franck-E** [comment]
Yes, that's exactely what I was doing, and not working for me, but no worries. I have hardcoded the api key into the environment.py file, and that works fine.
App is ok for basic stuff, but struggling with more advanced tasks, like try to ask it to list all connected monitors, it just fails...
Maybe

**Comment by legojesus** [comment]
Thanks for the update!

I’m curious as to why the .env file wasn’t working properly for you though, but anyways I’m glad you got around that.

as to the more complex stuff - on which operating system are you trying this? I assume Windows because on Windows such complex tasks often get butchered by ChatGPT’s attempts at CMD commands. On Linux these commands work like a charm.

For example, even asking “how much free space do I have left on my hard drive” is hard for it to accomplish via CMD. 

if you are indeed interested in better functionality, you can try and edit the functions of the bot to work with powershell instead of cmd (and change the genesis description as well so it would know to use powershell commands). You might find that it works better for such complex tasks but I refrained from using Powershell to limit its access and ability to damage the system by accident.
